version: "3.7"

services:
  diceroller:
    container_name: diceroller
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./api/:/api/"
    ports:
      - 8888:8888